Update workflow_TED.yml

diff --git a/.github/workflows/workflow_TED.yml b/.github/workflows/workflow_TED.yml
--- a/.github/workflows/workflow_TED.yml
+++ b/.github/workflows/workflow_TED.yml
@@ -21,12 +21,19 @@ jobs:
     - name: List files in the repository
       run: ls -R
 
+    - name: Verify script presence
+      run: |
+        if [ ! -f 0_main_global.py ]; then
+          echo "0_main_global.py not found!"
+          exit 1
+        fi
+
     - name: Duplicate the repository
       env:
         ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
       run: |
         REPO_NAME="TED_Pipeline"
-        REPLICATE_NAME="${REPO_NAME}_replicate"
+        REPLICATE_NAME="${REPO_NAME}_Replicate"
         USER_NAME="rtchamna"
         TARGET_USER="rtchamna"
 
@@ -43,20 +50,18 @@ jobs:
 
     - name: Run the main script
       run: |
+        cd TED_Pipeline  # Change to the directory containing the script if necessary
         python 0_main_global.py
 
     - name: Prepare for artifact upload
       run: |
         mkdir -p artifacts
         mv output/* artifacts/  # Adjust the path to your artifacts as needed
-      env:
-        REPO_NAME: "TED_Pipeline"
-        REPLICATE_NAME: "TED_Pipeline_replicate"
 
     - name: Checkout the replicated repository
       uses: actions/checkout@v2
       with:
-        repository: rtchamna/TED_Pipeline_replicate
+        repository: rtchamna/${REPLICATE_NAME}
         token: ${{ secrets.ACTIONS_PAT }}
         path: replicate_repo
 
